name: Python tests (no APIs)

on:
  push:
    branches: [ main, "**" ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: astral-sh/setup-uv@v4
      - name: Install dependencies
        run: uv sync --all-extras --dev
      - name: Run pytest (exclude smoke)
        run: uv run pytest -v -m "not smoke" --cov=src/lmsys_query_analysis --cov-report=term-missing --cov-fail-under=80


